# -*- coding: utf-8 -*-
"""robotMaze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZhGO-d51tPLo3uQ8PY73_cOk1TNFiOD
"""

#!pip install pygame

# set SDL to use the dummy NULL video driver, 
#   so it doesn't need a windowing system.
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"

from robotSimulation import RobotSimulation
from IPython.display import HTML
import AOLME
from google.colab.patches import cv2_imshow
      
if __name__ == '__main__':
    # Make a game instance, and run the game.
    frame_list = []
    gopi = RobotSimulation(frame_list)
    
    """ Type activities for robot movemxents:
        Move forward:  gopi.fw(second)
        Move backward: gopi.bw(second)
        Move left:     gopi.lt(second)
        Move right:    gopi.rt(second)
        Turn left:     gopi.ltd(degree)
        Turn right:    gopi.rtd(degree)
    """

   
    gopi.fw(8)
    gopi.ltd(150)
    gopi.lt(5)
    gopi.bw(2)
    gopi.rt(3)
    gopi.ltd(45)
    
    
    all_frame = gopi.frame_list
    #cv2_imshow(all_frame[10])
    print(len(all_frame))
    fps = 5
    play_video = AOLME.vid_show(all_frame, fps)
    


    #gopi.run_game()

HTML(play_video.to_html5_video())